// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjV8wIC579jpqdnFFNFffYSJAvnWcg2Uc',
    appId: '1:718395867355:android:31ff80248b6b2f481f4cfe',
    messagingSenderId: '718395867355',
    projectId: 'e-commerce-e7279',
    databaseURL: 'https://e-commerce-e7279-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-e7279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUk2k8xmPCv5YCmgNSQBXlIrwbSqrRRsA',
    appId: '1:718395867355:ios:7c31abf81b81e0b51f4cfe',
    messagingSenderId: '718395867355',
    projectId: 'e-commerce-e7279',
    databaseURL: 'https://e-commerce-e7279-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-e7279.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceShop',
  );
}
